volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        networks:
            - backend
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-postgres:
        image: postgres:16
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        networks:
            - backend
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    langgraph-api:
        image: rag_chatbot_langgraph-api:latest
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            OPENAI_API_KEY: "${OPENAI_API_KEY}"
            LANGSMITH_API_KEY: "${LANGSMITH_API_KEY}"
            TAVILY_API_KEY: "${TAVILY_API_KEY}"
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
        networks:
            - backend
        healthcheck:
            test: python /api/healthcheck.py
            interval: 60s
            start_interval: 1s
            start_period: 10s
        build:
            context: ./langgraph
            dockerfile: Dockerfile
    gradio-app:
        build:
            context: ./gradio
            dockerfile: Dockerfile
        depends_on:
            langgraph-api:
                condition: service_healthy
        environment:
            LANGSERVE_API_URL: "http://langgraph-api:8000"
            GRAPH_NAME: "rag_chatbot"
        ports:
            - "8501:8501"  # Map Gradio port to host for external access
        networks:
            - backend
        restart: unless-stopped

networks:
    backend:
        driver: bridge